### ISSUE TITLE
Reference to 'B' band not in data

### ISSUE THREAD

**Issue by Zeklandia** [jpierel14/snsed#5]
[Line 395 of colorCalc.py](https://github.com/jpierel14/snsed/blob/master/snsedextend/colorCalc.py#L395) appears to statically call upon the 'B' band, but that band does not always appear in the data.

```
Traceback (most recent call last):
  File "…/model_fitting_routines.py", line 378, in <module>
    color_tables_all = get_all_color_tables(data_photometry_all_formatted_snsedextend, dict_models_fit_best)
  File "…/model_fitting_routines.py", line 331, in get_all_color_tables
    effect_names=["host", "mw"]))
  File "…/anaconda3/envs/astro3/lib/python3.7/site-packages/snsedextend/colorCalc.py", line 395, in curveToColor
    t0=_getBandMaxTime(bestFit,fitted,bandDict,'B',zpMag.band_flux_to_mag(1,bandDict['B']),zpsys)
KeyError: 'B'
```

**Comment by jpierel14** [comment]
The time of peak is usually defined based on the B band magnitude, which is why it's hard-coded in. I'll make a small change that should fix this though, right now it looks like it depends on you sending the right banddict.

**Comment by Zeklandia** [comment]
Is there documentation on how to use the `bandDict` argument?

**Comment by jpierel14** [comment]
The documentation just says "sncosmo bandpass for each band used in the fitting/table generation", which is about right. It has the names of bands that are in your light curve as keys, and the corresponding name for that band in sncosmo as values. This is just in case you have strange band names and don't want to change them. 

I think in this case it would mean your bandDict would just have the same keys and values, which is sort of dumb. I just made an update to version 3.6, which should fix the original issue you had, plus you should be able to set bandDict=None, which should then assume that your light curve contains sncosmo bands.
